---

ansible:
  cfg:
    defaults:
      deprecation_warnings: false
  executor:
    args:
      ansible_playbook:
        - --inventory=inventory/
  playbooks:
    prepare: ../default/prepare.yml
    create: ../../../../molecule/playbooks/create.yml
    create-fail: ../../../../molecule/playbooks/create-fail.yml
    cleanup: ../../../../molecule/playbooks/cleanup.yml
    destroy: ../../../../molecule/playbooks/destroy.yml

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
