---

argument_specs:
  # roles/sshd/tasks/main.yml entry point
  main:
    short_description: The main entry point for the sshd role.
    options:
      sshd_configs:
        type: "list"
        elements: "dict"
        description: >-
          A list of dictionary to specify the filename and the content to write
          in the drop-in folder. For instance: [{name: 01-level.conf, content: 'option logLevel VERBOSE'},{...}]
        required: true
