---
galaxy_info:
  role_name: tmux
  namespace: epfl_si
  author: laurent.indermuehle@epfl.ch
  description: Configure tmux
  company: École Polytechnique Fédérale de Lausanne
  license: MIT
  min_ansible_version: '2.11'

  platforms:
    - name: EL
      versions:
        - '9'

  galaxy_tags: []

dependencies: []

collections: []
